#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
app_home:
    path: /home
    controller: App\Controller\HomeController::index
app_events:
    path: /events
    controller: App\Controller\ViewEventsController::index